/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.adfab.magebeans.guis;

import fr.adfab.magebeans.processes.CreateModuleProcess;
import java.io.FileNotFoundException;
import org.netbeans.api.project.Project;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.filesystems.FileObject;
import org.openide.util.Exceptions;
import org.openide.util.Lookup;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.openide.util.Utilities;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//fr.adfab.magebeans.guis//CreateModule//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "CreateModuleTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "fr.adfab.magebeans.guis.CreateModuleTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_CreateModuleAction",
        preferredID = "CreateModuleTopComponent"
)
@Messages({
    "CTL_CreateModuleAction=CreateModule",
    "CTL_CreateModuleTopComponent=CreateModule Window",
    "HINT_CreateModuleTopComponent=This is a CreateModule window"
})
public final class CreateModuleTopComponent extends TopComponent {

    public CreateModuleTopComponent() {
        initComponents();
        setName(Bundle.CTL_CreateModuleTopComponent());
        setToolTipText(Bundle.HINT_CreateModuleTopComponent());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rbtnCommunity = new javax.swing.JRadioButton();
        rbtnLocal = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txtCompany = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtModule = new javax.swing.JTextField();
        cboxSetup = new javax.swing.JCheckBox();
        cboxBlock = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        cboxModel = new javax.swing.JCheckBox();
        cboxHelper = new javax.swing.JCheckBox();
        cboxResourceModel = new javax.swing.JCheckBox();
        btnCreate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(CreateModuleTopComponent.class, "CreateModuleTopComponent.jLabel1.text")); // NOI18N

        buttonGroup1.add(rbtnCommunity);
        org.openide.awt.Mnemonics.setLocalizedText(rbtnCommunity, org.openide.util.NbBundle.getMessage(CreateModuleTopComponent.class, "CreateModuleTopComponent.rbtnCommunity.text")); // NOI18N

        buttonGroup1.add(rbtnLocal);
        org.openide.awt.Mnemonics.setLocalizedText(rbtnLocal, org.openide.util.NbBundle.getMessage(CreateModuleTopComponent.class, "CreateModuleTopComponent.rbtnLocal.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(CreateModuleTopComponent.class, "CreateModuleTopComponent.jLabel2.text")); // NOI18N

        txtCompany.setText(org.openide.util.NbBundle.getMessage(CreateModuleTopComponent.class, "CreateModuleTopComponent.txtCompany.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(CreateModuleTopComponent.class, "CreateModuleTopComponent.jLabel3.text")); // NOI18N

        txtModule.setText(org.openide.util.NbBundle.getMessage(CreateModuleTopComponent.class, "CreateModuleTopComponent.txtModule.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(cboxSetup, org.openide.util.NbBundle.getMessage(CreateModuleTopComponent.class, "CreateModuleTopComponent.cboxSetup.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(cboxBlock, org.openide.util.NbBundle.getMessage(CreateModuleTopComponent.class, "CreateModuleTopComponent.cboxBlock.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(CreateModuleTopComponent.class, "CreateModuleTopComponent.jLabel4.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(cboxModel, org.openide.util.NbBundle.getMessage(CreateModuleTopComponent.class, "CreateModuleTopComponent.cboxModel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(cboxHelper, org.openide.util.NbBundle.getMessage(CreateModuleTopComponent.class, "CreateModuleTopComponent.cboxHelper.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(cboxResourceModel, org.openide.util.NbBundle.getMessage(CreateModuleTopComponent.class, "CreateModuleTopComponent.cboxResourceModel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(btnCreate, org.openide.util.NbBundle.getMessage(CreateModuleTopComponent.class, "CreateModuleTopComponent.btnCreate.text")); // NOI18N
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(btnCancel, org.openide.util.NbBundle.getMessage(CreateModuleTopComponent.class, "CreateModuleTopComponent.btnCancel.text")); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboxBlock)
                        .addGap(18, 18, 18)
                        .addComponent(cboxModel)
                        .addGap(18, 18, 18)
                        .addComponent(cboxHelper))
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboxResourceModel)
                        .addGap(18, 18, 18)
                        .addComponent(cboxSetup))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnCreate)
                            .addGap(18, 18, 18)
                            .addComponent(btnCancel))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rbtnCommunity)
                                    .addGap(35, 35, 35)
                                    .addComponent(rbtnLocal))
                                .addComponent(txtCompany)
                                .addComponent(txtModule, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rbtnCommunity)
                    .addComponent(rbtnLocal))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtModule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxBlock)
                    .addComponent(cboxModel)
                    .addComponent(cboxHelper))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxSetup)
                    .addComponent(cboxResourceModel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(btnCancel))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(CreateModuleTopComponent.class, "CreateModuleTopComponent.jLabel1.AccessibleContext.accessibleName")); // NOI18N
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        ((CreateModuleTopComponent) btnCancel.getParent()).close();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        CreateModuleProcess createModuleProcess = new CreateModuleProcess();
        
        String codePool = "local";
        if (rbtnCommunity.isSelected()) {
            codePool = "community";
        }
        
        try {
            createModuleProcess.setProjectDir(this.projectDir);
            createModuleProcess.setCodePool(codePool);
            createModuleProcess.setCompany(txtCompany.getText());
            createModuleProcess.setModule(txtModule.getText());
            
            if (cboxBlock.isSelected()) {
                createModuleProcess.setHasBlock(true);
            }
            
            if (cboxModel.isSelected()) {
                createModuleProcess.setHasModel(true);
            }
            
            if (cboxHelper.isSelected()) {
                createModuleProcess.setHasHelper(true);
            }
            
            if (cboxSetup.isSelected()) {
                createModuleProcess.setHasSetup(true);
            }
            
            createModuleProcess.process();
        } catch (FileNotFoundException | IllegalArgumentException ex) {
            Exceptions.printStackTrace(ex);
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    protected String projectDir = "";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cboxBlock;
    private javax.swing.JCheckBox cboxHelper;
    private javax.swing.JCheckBox cboxModel;
    private javax.swing.JCheckBox cboxResourceModel;
    private javax.swing.JCheckBox cboxSetup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton rbtnCommunity;
    private javax.swing.JRadioButton rbtnLocal;
    private javax.swing.JTextField txtCompany;
    private javax.swing.JTextField txtModule;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }
    
    public void setProjectDir(String projectDir) {
        this.projectDir = projectDir;
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
